<?php
namespace App\Http\Controllers\Api\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreStaffEvaluationRequest;
use App\Models\StaffEvaluation;
use App\Models\StaffEvaluationCriterion;
use App\Models\StaffMember;
use App\Services\AuditLogService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class StaffEvaluationController extends Controller
{
    public function __construct(private readonly AuditLogService $audit = new AuditLogService()) {}
    public function criteria(): JsonResponse { return response()->json(StaffEvaluationCriterion::query()->orderBy('sort_order')->orderBy('name')->get()); }
    public function storeCriterion(Request $request): JsonResponse { $item=StaffEvaluationCriterion::query()->create($this->criterionData($request)); $this->auditCriterion($request,'create',$item); return response()->json($item,201); }
    public function updateCriterion(Request $request, StaffEvaluationCriterion $criterion): JsonResponse { abort_unless(!$request->has('code') || $request->input('code')===$criterion->code,422,'Il codice del criterio non è modificabile.'); $before=$criterion->only(['code','name','description','is_active','sort_order']); $criterion->update($this->criterionData($request,$criterion->id,false)); $this->auditCriterion($request,'update',$criterion,$before); return response()->json($criterion->fresh()); }
    public function destroyCriterion(Request $request, StaffEvaluationCriterion $criterion): JsonResponse { abort_if($criterion->scores()->exists(),409,'Il criterio è già utilizzato in una valutazione e può solo essere disattivato.'); $before=$criterion->only(['code','name','description','is_active','sort_order']); $criterion->delete(); $this->auditCriterion($request,'delete',$criterion,$before); return response()->json(status:204); }
    public function index(StaffMember $staffMember): JsonResponse { $items=$staffMember->evaluations()->with(['evaluator:id,first_name,last_name,email','finalizedBy:id,first_name,last_name,email','scores.criterion'])->latest('period_end')->get(); $this->record($this->request(),'read',$staffMember,null,'ha consultato le valutazioni HR'); return response()->json($items); }
    public function store(StoreStaffEvaluationRequest $request, StaffMember $staffMember): JsonResponse { $evaluation=DB::transaction(function() use($request,$staffMember){ $data=$request->validated(); $data += ['facility_id'=>$staffMember->facility_id,'staff_member_id'=>$staffMember->id,'evaluator_user_id'=>$request->user()->id,'status'=>'DRAFT']; $evaluation=StaffEvaluation::query()->create($data); $this->syncScores($evaluation,$data['scores']); return $evaluation; }); $evaluation=$this->load($evaluation); $this->record($request,'create',$staffMember,$evaluation,'ha creato la bozza di valutazione HR'); return response()->json($evaluation,201); }
    public function show(Request $request, StaffMember $staffMember, StaffEvaluation $evaluation): JsonResponse { $this->belongsTo($staffMember,$evaluation); $this->record($request,'read',$staffMember,$evaluation,'ha visualizzato la valutazione HR'); return response()->json($this->load($evaluation)); }
    public function update(StoreStaffEvaluationRequest $request, StaffMember $staffMember, StaffEvaluation $evaluation): JsonResponse { $this->belongsTo($staffMember,$evaluation); $this->assertDraft($evaluation); $before=$this->snapshot($evaluation); DB::transaction(function()use($request,$evaluation){$data=$request->validated();$evaluation->update($data);$this->syncScores($evaluation,$data['scores']);}); $evaluation=$this->load($evaluation); $this->record($request,'update',$staffMember,$evaluation,'ha aggiornato la bozza di valutazione HR',$before); return response()->json($evaluation); }
    public function finalize(Request $request, StaffMember $staffMember, StaffEvaluation $evaluation): JsonResponse { $this->belongsTo($staffMember,$evaluation); $this->assertDraft($evaluation); $before=$this->snapshot($evaluation); $evaluation->update(['status'=>'FINALIZED','finalized_at'=>now(),'finalized_by_user_id'=>$request->user()->id]); $evaluation=$this->load($evaluation); $this->record($request,'finalize',$staffMember,$evaluation,'ha finalizzato la valutazione HR con firma applicativa',$before); return response()->json($evaluation); }
    public function destroy(Request $request, StaffMember $staffMember, StaffEvaluation $evaluation): JsonResponse { $this->belongsTo($staffMember,$evaluation); $this->assertDraft($evaluation); $before=$this->snapshot($evaluation); $evaluation->delete(); $this->record($request,'delete',$staffMember,$evaluation,'ha archiviato la bozza di valutazione HR',$before); return response()->json(status:204); }
    private function criterionData(Request $request, ?int $id=null, bool $require=true): array { $data=Validator::make($request->all(),['code'=>[$require?'required':'sometimes','string','max:50',Rule::unique('staff_evaluation_criteria','code')->ignore($id)],'name'=>['required','string','max:100'],'description'=>['nullable','string'],'is_active'=>['nullable','boolean'],'sort_order'=>['nullable','integer','min:0']])->validate(); return $data+['is_active'=>$request->boolean('is_active',true),'sort_order'=>$request->integer('sort_order',100)]; }
    private function syncScores(StaffEvaluation $evaluation,array $scores):void{$evaluation->scores()->delete();$evaluation->scores()->createMany(collect($scores)->map(fn($item)=>['staff_evaluation_criterion_id'=>$item['criterion_id'],'score'=>$item['score'],'notes'=>$item['notes']??null])->all());$evaluation->update(['overall_score'=>round(collect($scores)->avg('score'),2)]);}
    private function load(StaffEvaluation $item):StaffEvaluation{return $item->fresh(['evaluator:id,first_name,last_name,email','finalizedBy:id,first_name,last_name,email','scores.criterion']);}
    private function belongsTo(StaffMember $staff,StaffEvaluation $item):void{abort_unless($item->staff_member_id===$staff->id,404);}
    private function assertDraft(StaffEvaluation $item):void{abort_if($item->status==='FINALIZED',409,'La valutazione è già finalizzata e non può essere modificata o archiviata.');}
    private function snapshot(StaffEvaluation $item):array{return ['period_start'=>$item->period_start?->toDateString(),'period_end'=>$item->period_end?->toDateString(),'evaluation_date'=>$item->evaluation_date?->toDateString(),'status'=>$item->status,'overall_score'=>$item->overall_score,'scores'=>$item->scores()->get(['staff_evaluation_criterion_id','score'])->toArray()];}
    private function record(Request $request,string $action,StaffMember $staff,?StaffEvaluation $evaluation,string $verb,?array $before=null):void{$this->audit->record($request,['facility_id'=>$staff->facility_id,'action'=>$action,'resource_type'=>'staff_evaluation','resource_id'=>$evaluation?(string)$evaluation->id:null,'resource_label'=>trim($staff->first_name.' '.$staff->last_name),'operation_summary'=>$this->audit->resolveActorDisplayName($request->user()).' '.$verb.' del professionista '.trim($staff->first_name.' '.$staff->last_name).'.','old_values_json'=>$before,'new_values_json'=>$evaluation?$this->snapshot($evaluation):null]);$this->audit->markHandled($request);}
    private function auditCriterion(Request $request,string $action,StaffEvaluationCriterion $item,?array $before=null):void{$this->audit->record($request,['action'=>$action,'resource_type'=>'staff_evaluation_criterion','resource_id'=>(string)$item->id,'resource_label'=>$item->name,'operation_summary'=>$this->audit->resolveActorDisplayName($request->user()).' ha '.$action.' il criterio di valutazione '.$item->name.'.','old_values_json'=>$before,'new_values_json'=>$action==='delete'?null:$item->only(['code','name','description','is_active','sort_order'])]);$this->audit->markHandled($request);}
    private function request(): Request { return request(); }
}
