<?php

namespace Database\Seeders;

use App\Models\Permission;
use App\Models\Role;
use Illuminate\Database\Seeder;

class RbacSeeder extends Seeder
{
    public function run(): void
    {
        $roles = [
            'SUPER_ADMIN' => 'Accesso totale multi-struttura',
            'DIRETTORE' => 'Accesso completo alla singola struttura',
            'COORDINATORE' => 'Gestione operativa della struttura',
            'REFERENTE_STRUTTURA' => 'Gestione operativa della struttura con perimetro equivalente al coordinatore',
            'PSICOLOGO' => 'Accesso ai profili psico-clinici',
            'PEDIATRA' => 'Accesso clinico sanitario limitato ai minori assegnati',
            'EDUCATORE' => 'Operatività educativa quotidiana',
            'EDUCATORE_NOTTURNO' => 'Operatività notturna ridotta',
            'ASSISTENTE_SOCIALE_EST' => 'Accesso esterno in sola lettura',
            'SUPERVISORE_ESTERNO' => 'Report aggregati anonimi',
            'ADMIN_IT' => 'Gestione tecnica senza accesso ai minori',
        ];

        $permissions = [
            ['resource' => 'organizations', 'action' => 'create'],
            ['resource' => 'organizations', 'action' => 'read'],
            ['resource' => 'facilities', 'action' => 'create'],
            ['resource' => 'facilities', 'action' => 'read'],
            ['resource' => 'facilities', 'action' => 'update'],
            ['resource' => 'users', 'action' => 'create'],
            ['resource' => 'users', 'action' => 'read'],
            ['resource' => 'users', 'action' => 'update'],
            ['resource' => 'document_types', 'action' => 'create'],
            ['resource' => 'document_types', 'action' => 'read'],
            ['resource' => 'document_types', 'action' => 'update'],
            ['resource' => 'document_types', 'action' => 'delete'],
            ['resource' => 'document_classifications', 'action' => 'create'],
            ['resource' => 'document_classifications', 'action' => 'read'],
            ['resource' => 'document_classifications', 'action' => 'update'],
            ['resource' => 'document_classifications', 'action' => 'delete'],
            ['resource' => 'document_access_matrix', 'action' => 'read'],
            ['resource' => 'role_document_policies', 'action' => 'read'],
            ['resource' => 'role_document_policies', 'action' => 'update'],
            ['resource' => 'contact_types', 'action' => 'create'],
            ['resource' => 'contact_types', 'action' => 'read'],
            ['resource' => 'contact_types', 'action' => 'update'],
            ['resource' => 'contact_types', 'action' => 'delete'],
            ['resource' => 'minor_statuses', 'action' => 'create'],
            ['resource' => 'minor_statuses', 'action' => 'read'],
            ['resource' => 'minor_statuses', 'action' => 'update'],
            ['resource' => 'minor_statuses', 'action' => 'delete'],
            ['resource' => 'gender_identities', 'action' => 'create'],
            ['resource' => 'gender_identities', 'action' => 'read'],
            ['resource' => 'gender_identities', 'action' => 'update'],
            ['resource' => 'gender_identities', 'action' => 'delete'],
            ['resource' => 'biological_sexes', 'action' => 'create'],
            ['resource' => 'biological_sexes', 'action' => 'read'],
            ['resource' => 'biological_sexes', 'action' => 'update'],
            ['resource' => 'biological_sexes', 'action' => 'delete'],
            ['resource' => 'exit_types', 'action' => 'create'],
            ['resource' => 'exit_types', 'action' => 'read'],
            ['resource' => 'exit_types', 'action' => 'update'],
            ['resource' => 'exit_types', 'action' => 'delete'],
            ['resource' => 'geography', 'action' => 'create'],
            ['resource' => 'geography', 'action' => 'read'],
            ['resource' => 'geography', 'action' => 'update'],
            ['resource' => 'geography', 'action' => 'delete'],
            ['resource' => 'geography_sync', 'action' => 'read'],
            ['resource' => 'geography_sync', 'action' => 'run'],
            ['resource' => 'geography_sync', 'action' => 'publish'],
            ['resource' => 'geography_providers', 'action' => 'create'],
            ['resource' => 'geography_providers', 'action' => 'read'],
            ['resource' => 'geography_providers', 'action' => 'update'],
            ['resource' => 'geography_providers', 'action' => 'delete'],
            ['resource' => 'roles', 'action' => 'create'],
            ['resource' => 'roles', 'action' => 'read'],
            ['resource' => 'roles', 'action' => 'update'],
            ['resource' => 'roles', 'action' => 'delete'],
            ['resource' => 'role_permissions', 'action' => 'read'],
            ['resource' => 'role_permissions', 'action' => 'update'],
            ['resource' => 'roles', 'action' => 'assign'],
            ['resource' => 'user_facility_roles', 'action' => 'create'],
            ['resource' => 'user_facility_roles', 'action' => 'read'],
            ['resource' => 'user_facility_roles', 'action' => 'update'],
            ['resource' => 'user_facility_roles', 'action' => 'revoke'],
            ['resource' => 'staff_members', 'action' => 'create'],
            ['resource' => 'staff_members', 'action' => 'read'],
            ['resource' => 'staff_members', 'action' => 'update'],
            ['resource' => 'staff_members', 'action' => 'delete'],
            ['resource' => 'minor_user_assignments', 'action' => 'create'],
            ['resource' => 'minor_user_assignments', 'action' => 'read'],
            ['resource' => 'minor_user_assignments', 'action' => 'update'],
            ['resource' => 'minor_user_assignments', 'action' => 'revoke'],
            ['resource' => 'minors', 'action' => 'create'],
            ['resource' => 'minors', 'action' => 'read'],
            ['resource' => 'minors', 'action' => 'update'],
            ['resource' => 'minor_profiles', 'action' => 'read'],
            ['resource' => 'minor_profiles', 'action' => 'update'],
            ['resource' => 'minor_contacts', 'action' => 'create'],
            ['resource' => 'minor_contacts', 'action' => 'read'],
            ['resource' => 'minor_contacts', 'action' => 'update'],
            ['resource' => 'attachments', 'action' => 'upload'],
            ['resource' => 'attachments', 'action' => 'read'],
            ['resource' => 'attachments', 'action' => 'download'],
            ['resource' => 'minor_exits', 'action' => 'create'],
            ['resource' => 'minor_exits', 'action' => 'read'],
            ['resource' => 'minor_exits', 'action' => 'update'],
            ['resource' => 'minor_exits', 'action' => 'delete'],
            ['resource' => 'activity_types', 'action' => 'create'],
            ['resource' => 'activity_types', 'action' => 'read'],
            ['resource' => 'activity_types', 'action' => 'update'],
            ['resource' => 'activity_types', 'action' => 'delete'],
            ['resource' => 'approach_types', 'action' => 'create'],
            ['resource' => 'approach_types', 'action' => 'read'],
            ['resource' => 'approach_types', 'action' => 'update'],
            ['resource' => 'approach_types', 'action' => 'delete'],
            ['resource' => 'journal_entry_types', 'action' => 'create'],
            ['resource' => 'journal_entry_types', 'action' => 'read'],
            ['resource' => 'journal_entry_types', 'action' => 'update'],
            ['resource' => 'journal_entry_types', 'action' => 'delete'],
            ['resource' => 'staff_shift_templates', 'action' => 'create'],
            ['resource' => 'staff_shift_templates', 'action' => 'read'],
            ['resource' => 'staff_shift_templates', 'action' => 'update'],
            ['resource' => 'staff_shift_templates', 'action' => 'delete'],
            ['resource' => 'staff_shift_assignments', 'action' => 'create'],
            ['resource' => 'staff_shift_assignments', 'action' => 'read'],
            ['resource' => 'staff_shift_assignments', 'action' => 'update'],
            ['resource' => 'staff_shift_assignments', 'action' => 'delete'],
            ['resource' => 'staff_attendance_events', 'action' => 'create'],
            ['resource' => 'staff_attendance_events', 'action' => 'read'],
            ['resource' => 'staff_attendance_events', 'action' => 'update'],
            ['resource' => 'staff_timesheet_entries', 'action' => 'read'],
            ['resource' => 'staff_timesheet_entries', 'action' => 'update'],
            ['resource' => 'staff_timesheet_entries', 'action' => 'submit'],
            ['resource' => 'staff_timesheet_entries', 'action' => 'approve'],
            ['resource' => 'staff_timesheet_entries', 'action' => 'lock'],
            ['resource' => 'staff_timesheet_entries', 'action' => 'export'],
            ['resource' => 'staff_timesheet_adjustments', 'action' => 'create'],
            ['resource' => 'staff_timesheet_adjustments', 'action' => 'read'],
            ['resource' => 'staff_timesheet_adjustments', 'action' => 'update'],
            ['resource' => 'staff_timesheet_adjustments', 'action' => 'approve'],
            ['resource' => 'staff_timesheet_exports', 'action' => 'create'],
            ['resource' => 'staff_timesheet_exports', 'action' => 'read'],
            ['resource' => 'minor_activities', 'action' => 'create'],
            ['resource' => 'minor_activities', 'action' => 'read'],
            ['resource' => 'minor_activities', 'action' => 'update'],
            ['resource' => 'minor_activities', 'action' => 'delete'],
            ['resource' => 'minor_approaches', 'action' => 'create'],
            ['resource' => 'minor_approaches', 'action' => 'read'],
            ['resource' => 'minor_approaches', 'action' => 'update'],
            ['resource' => 'minor_approaches', 'action' => 'delete'],
            ['resource' => 'minor_journals', 'action' => 'create'],
            ['resource' => 'minor_journals', 'action' => 'read'],
            ['resource' => 'minor_journals', 'action' => 'update'],
            ['resource' => 'minor_journals', 'action' => 'delete'],
            ['resource' => 'internal_messages', 'action' => 'create'],
            ['resource' => 'internal_messages', 'action' => 'read'],
            ['resource' => 'internal_messages', 'action' => 'update'],
            ['resource' => 'internal_messages', 'action' => 'delete'],
            ['resource' => 'audit_logs', 'action' => 'read'],
            ['resource' => 'database_backups', 'action' => 'read'],
            ['resource' => 'database_backups', 'action' => 'create'],
            ['resource' => 'database_backups', 'action' => 'restore'],
            ['resource' => 'system_storage', 'action' => 'read'],
            ['resource' => 'system_storage', 'action' => 'create'],
            ['resource' => 'system_storage', 'action' => 'update'],
            ['resource' => 'system_storage', 'action' => 'activate'],
            ['resource' => 'system_storage', 'action' => 'test'],
            ['resource' => 'system_storage', 'action' => 'delete'],
            ['resource' => 'system_health', 'action' => 'read'],
            ['resource' => 'system_health', 'action' => 'run'],
            ['resource' => 'staff_evaluations', 'action' => 'read'],
            ['resource' => 'staff_evaluations', 'action' => 'manage'],
            ['resource' => 'facility_bulletins', 'action' => 'read'],
            ['resource' => 'facility_bulletins', 'action' => 'manage'],
            ['resource' => 'facility_bulletins', 'action' => 'publish'],
            ['resource' => 'facility_bulletins', 'action' => 'acknowledge'],
            ['resource' => 'incident_types', 'action' => 'create'],
            ['resource' => 'incident_types', 'action' => 'read'],
            ['resource' => 'incident_types', 'action' => 'update'],
            ['resource' => 'incident_types', 'action' => 'delete'],
            ['resource' => 'minor_incidents', 'action' => 'create'],
            ['resource' => 'minor_incidents', 'action' => 'read'],
            ['resource' => 'minor_incidents', 'action' => 'update'],
            ['resource' => 'minor_incidents', 'action' => 'export'],
            ['resource' => 'medication_catalog', 'action' => 'create'],
            ['resource' => 'medication_catalog', 'action' => 'read'],
            ['resource' => 'medication_catalog', 'action' => 'update'],
            ['resource' => 'medication_catalog', 'action' => 'delete'],
            ['resource' => 'minor_health', 'action' => 'create'],
            ['resource' => 'minor_health', 'action' => 'read'],
            ['resource' => 'minor_health', 'action' => 'update'],
            ['resource' => 'minor_health', 'action' => 'administer'],
            ['resource' => 'minor_health', 'action' => 'export'],
        ];

        $roleModels = collect($roles)->mapWithKeys(function (string $description, string $code) {
            $role = Role::query()->updateOrCreate(
                ['code' => $code],
                [
                    'name' => str($code)->replace('_', ' ')->title()->toString(),
                    'description' => $description,
                    'is_system' => true,
                ],
            );

            return [$code => $role];
        });

        $permissionModels = collect($permissions)->mapWithKeys(function (array $permission) {
            $code = "{$permission['resource']}.{$permission['action']}";

            $model = Permission::query()->updateOrCreate(
                ['code' => $code],
                [
                    'resource' => $permission['resource'],
                    'action' => $permission['action'],
                    'description' => str($code)->replace('.', ' ')->replace('_', ' ')->title()->toString(),
                ],
            );

            return [$code => $model];
        });

        $grants = [
            'SUPER_ADMIN' => $permissionModels->keys()->all(),
            'ADMIN_IT' => [
                'organizations.read',
                'organizations.create',
                'facilities.read',
                'document_types.create',
                'document_types.read',
                'document_types.update',
                'document_types.delete',
                'document_classifications.create',
                'document_classifications.read',
                'document_classifications.update',
                'document_classifications.delete',
                'document_access_matrix.read',
                'role_document_policies.read',
                'role_document_policies.update',
                'contact_types.create',
                'contact_types.read',
                'contact_types.update',
                'contact_types.delete',
                'minor_statuses.create',
                'minor_statuses.read',
                'minor_statuses.update',
                'minor_statuses.delete',
                'gender_identities.create',
                'gender_identities.read',
                'gender_identities.update',
                'gender_identities.delete',
                'biological_sexes.create',
                'biological_sexes.read',
                'biological_sexes.update',
                'biological_sexes.delete',
                'exit_types.create',
                'exit_types.read',
                'exit_types.update',
                'exit_types.delete',
                'activity_types.create',
                'activity_types.read',
                'activity_types.update',
                'activity_types.delete',
                'approach_types.create',
                'approach_types.read',
                'approach_types.update',
                'approach_types.delete',
                'journal_entry_types.create',
                'journal_entry_types.read',
                'journal_entry_types.update',
                'journal_entry_types.delete',
                'staff_shift_templates.create',
                'staff_shift_templates.read',
                'staff_shift_templates.update',
                'staff_shift_templates.delete',
                'staff_shift_assignments.create',
                'staff_shift_assignments.read',
                'staff_shift_assignments.update',
                'staff_shift_assignments.delete',
                'staff_attendance_events.create',
                'staff_attendance_events.read',
                'staff_attendance_events.update',
                'staff_timesheet_entries.read',
                'staff_timesheet_entries.update',
                'staff_timesheet_entries.submit',
                'staff_timesheet_entries.approve',
                'staff_timesheet_entries.lock',
                'staff_timesheet_entries.export',
                'staff_timesheet_adjustments.create',
                'staff_timesheet_adjustments.read',
                'staff_timesheet_adjustments.update',
                'staff_timesheet_adjustments.approve',
                'staff_timesheet_exports.create',
                'staff_timesheet_exports.read',
                'geography.create',
                'geography.read',
                'geography.update',
                'geography.delete',
                'geography_sync.read',
                'geography_sync.run',
                'geography_sync.publish',
                'geography_providers.create',
                'geography_providers.read',
                'geography_providers.update',
                'geography_providers.delete',
                'users.create',
                'users.read',
                'users.update',
                'roles.create',
                'roles.read',
                'roles.update',
                'roles.delete',
                'role_permissions.read',
                'role_permissions.update',
                'document_classifications.create',
                'document_classifications.read',
                'document_classifications.update',
                'document_classifications.delete',
                'document_access_matrix.read',
                'role_document_policies.read',
                'role_document_policies.update',
                'roles.assign',
                'user_facility_roles.create',
                'user_facility_roles.read',
                'user_facility_roles.update',
                'user_facility_roles.revoke',
                'minor_user_assignments.create',
                'minor_user_assignments.read',
                'minor_user_assignments.update',
                'minor_user_assignments.revoke',
                'audit_logs.read',
                'database_backups.read',
                'database_backups.create',
                'database_backups.restore',
                'system_storage.read',
                'system_storage.create',
                'system_storage.update',
                'system_storage.activate',
                'system_storage.test',
                'system_storage.delete',
                'system_health.read',
                'system_health.run',
                'staff_shift_templates.create',
                'staff_shift_templates.read',
                'staff_shift_templates.update',
                'staff_shift_templates.delete',
                'staff_shift_assignments.create',
                'staff_shift_assignments.read',
                'staff_shift_assignments.update',
                'staff_shift_assignments.delete',
                'staff_attendance_events.create',
                'staff_attendance_events.read',
                'staff_attendance_events.update',
                'staff_timesheet_entries.read',
                'staff_timesheet_entries.update',
                'staff_timesheet_entries.submit',
                'staff_timesheet_entries.approve',
                'staff_timesheet_entries.lock',
                'staff_timesheet_entries.export',
                'staff_timesheet_adjustments.create',
                'staff_timesheet_adjustments.read',
                'staff_timesheet_adjustments.update',
                'staff_timesheet_adjustments.approve',
                'staff_timesheet_exports.create',
                'staff_timesheet_exports.read',
            ],
            'DIRETTORE' => [
                'facilities.read',
                'document_classifications.read',
                'document_classifications.create',
                'document_classifications.update',
                'document_access_matrix.read',
                'role_document_policies.read',
                'role_document_policies.update',
                'staff_members.create',
                'staff_members.read',
                'staff_members.update',
                'staff_members.delete',
                'minors.create',
                'minors.read',
                'minors.update',
                'minor_profiles.read',
                'minor_profiles.update',
                'minor_contacts.create',
                'minor_contacts.read',
                'minor_contacts.update',
                'attachments.upload',
                'attachments.read',
                'attachments.download',
                'minor_exits.create',
                'minor_exits.read',
                'minor_exits.update',
                'minor_exits.delete',
                'minor_activities.create',
                'minor_activities.read',
                'minor_activities.update',
                'minor_activities.delete',
                'minor_approaches.create',
                'minor_approaches.read',
                'minor_approaches.update',
                'minor_approaches.delete',
                'minor_journals.create',
                'minor_journals.read',
                'minor_journals.update',
                'minor_journals.delete',
                'staff_shift_templates.create',
                'staff_shift_templates.read',
                'staff_shift_templates.update',
                'staff_shift_templates.delete',
                'staff_shift_assignments.create',
                'staff_shift_assignments.read',
                'staff_shift_assignments.update',
                'staff_shift_assignments.delete',
                'staff_attendance_events.create',
                'staff_attendance_events.read',
                'staff_attendance_events.update',
                'staff_timesheet_entries.read',
                'staff_timesheet_entries.update',
                'staff_timesheet_entries.submit',
                'staff_timesheet_entries.approve',
                'staff_timesheet_entries.lock',
                'staff_timesheet_entries.export',
                'staff_timesheet_adjustments.create',
                'staff_timesheet_adjustments.read',
                'staff_timesheet_adjustments.update',
                'staff_timesheet_adjustments.approve',
                'staff_timesheet_exports.create',
                'staff_timesheet_exports.read',
                'internal_messages.create',
                'internal_messages.read',
                'internal_messages.update',
                'internal_messages.delete',
                'audit_logs.read',
                'database_backups.read',
                'database_backups.create',
                'database_backups.restore',
                'system_storage.read',
                'system_storage.create',
                'system_storage.update',
                'system_storage.activate',
                'system_storage.test',
                'system_health.read',
                'system_health.run',
            ],
            'COORDINATORE' => [
                'facilities.read',
                'document_classifications.read',
                'document_classifications.create',
                'document_classifications.update',
                'document_access_matrix.read',
                'role_document_policies.read',
                'role_document_policies.update',
                'users.create',
                'users.read',
                'users.update',
                'roles.read',
                'user_facility_roles.create',
                'user_facility_roles.read',
                'user_facility_roles.update',
                'user_facility_roles.revoke',
                'staff_members.create',
                'staff_members.read',
                'staff_members.update',
                'minor_user_assignments.create',
                'minor_user_assignments.read',
                'minor_user_assignments.update',
                'minor_user_assignments.revoke',
                'minors.create',
                'minors.read',
                'minors.update',
                'minor_profiles.read',
                'minor_profiles.update',
                'minor_contacts.create',
                'minor_contacts.read',
                'minor_contacts.update',
                'attachments.upload',
                'attachments.read',
                'attachments.download',
                'minor_exits.create',
                'minor_exits.read',
                'minor_exits.update',
                'minor_activities.create',
                'minor_activities.read',
                'minor_activities.update',
                'minor_approaches.create',
                'minor_approaches.read',
                'minor_approaches.update',
                'minor_journals.create',
                'minor_journals.read',
                'minor_journals.update',
                'staff_shift_templates.create',
                'staff_shift_templates.read',
                'staff_shift_templates.update',
                'staff_shift_assignments.create',
                'staff_shift_assignments.read',
                'staff_shift_assignments.update',
                'staff_attendance_events.read',
                'staff_timesheet_entries.read',
                'staff_timesheet_entries.update',
                'staff_timesheet_entries.approve',
                'staff_timesheet_entries.export',
                'staff_timesheet_adjustments.create',
                'staff_timesheet_adjustments.read',
                'staff_timesheet_adjustments.update',
                'staff_timesheet_adjustments.approve',
                'staff_timesheet_exports.create',
                'staff_timesheet_exports.read',
                'internal_messages.create',
                'internal_messages.read',
                'internal_messages.update',
                'database_backups.read',
                'database_backups.create',
                'system_storage.read',
                'system_storage.test',
                'system_health.read',
                'system_health.run',
            ],
            'REFERENTE_STRUTTURA' => [
                'facilities.read',
                'document_classifications.read',
                'document_classifications.create',
                'document_classifications.update',
                'document_access_matrix.read',
                'role_document_policies.read',
                'role_document_policies.update',
                'users.create',
                'users.read',
                'users.update',
                'roles.read',
                'user_facility_roles.create',
                'user_facility_roles.read',
                'user_facility_roles.update',
                'user_facility_roles.revoke',
                'staff_members.create',
                'staff_members.read',
                'staff_members.update',
                'minor_user_assignments.create',
                'minor_user_assignments.read',
                'minor_user_assignments.update',
                'minor_user_assignments.revoke',
                'minors.create',
                'minors.read',
                'minors.update',
                'minor_profiles.read',
                'minor_profiles.update',
                'minor_contacts.create',
                'minor_contacts.read',
                'minor_contacts.update',
                'attachments.upload',
                'attachments.read',
                'attachments.download',
                'minor_exits.create',
                'minor_exits.read',
                'minor_exits.update',
                'minor_activities.create',
                'minor_activities.read',
                'minor_activities.update',
                'minor_approaches.create',
                'minor_approaches.read',
                'minor_approaches.update',
                'minor_journals.create',
                'minor_journals.read',
                'minor_journals.update',
                'staff_shift_templates.create',
                'staff_shift_templates.read',
                'staff_shift_templates.update',
                'staff_shift_assignments.create',
                'staff_shift_assignments.read',
                'staff_shift_assignments.update',
                'staff_attendance_events.read',
                'staff_timesheet_entries.read',
                'staff_timesheet_entries.update',
                'staff_timesheet_entries.approve',
                'staff_timesheet_entries.export',
                'staff_timesheet_adjustments.create',
                'staff_timesheet_adjustments.read',
                'staff_timesheet_adjustments.update',
                'staff_timesheet_adjustments.approve',
                'staff_timesheet_exports.create',
                'staff_timesheet_exports.read',
                'internal_messages.create',
                'internal_messages.read',
                'internal_messages.update',
                'database_backups.read',
                'database_backups.create',
                'system_storage.read',
                'system_storage.test',
                'system_health.read',
                'system_health.run',
            ],
            'PSICOLOGO' => [
                'facilities.read',
                'minors.read',
                'minor_profiles.read',
                'minor_profiles.update',
                'attachments.read',
                'attachments.download',
                'minor_exits.read',
                'minor_activities.read',
                'minor_activities.update',
                'minor_approaches.read',
                'minor_approaches.update',
                'minor_journals.read',
                'minor_journals.update',
                'staff_shift_assignments.read',
                'staff_attendance_events.read',
                'staff_timesheet_entries.read',
                'internal_messages.create',
                'internal_messages.read',
                'internal_messages.update',
            ],
            'PEDIATRA' => [
                'facilities.read',
                'minors.read',
                'minor_profiles.read',
                'attachments.read',
                'attachments.download',
                'minor_exits.read',
                'minor_activities.read',
                'internal_messages.read',
                'staff_timesheet_entries.read',
            ],
            'EDUCATORE' => [
                'facilities.read',
                'staff_members.read',
                'staff_members.update',
                'minors.read',
                'minor_contacts.create',
                'minor_contacts.read',
                'minor_contacts.update',
                'attachments.upload',
                'attachments.read',
                'minor_exits.create',
                'minor_exits.read',
                'minor_exits.update',
                'minor_activities.create',
                'minor_activities.read',
                'minor_activities.update',
                'minor_approaches.create',
                'minor_approaches.read',
                'minor_approaches.update',
                'minor_journals.create',
                'minor_journals.read',
                'minor_journals.update',
                'staff_shift_assignments.read',
                'staff_attendance_events.create',
                'staff_attendance_events.read',
                'staff_attendance_events.update',
                'staff_timesheet_entries.read',
                'staff_timesheet_entries.submit',
                'staff_timesheet_adjustments.create',
                'staff_timesheet_adjustments.read',
                'internal_messages.create',
                'internal_messages.read',
                'internal_messages.update',
            ],
            'EDUCATORE_NOTTURNO' => [
                'facilities.read',
                'minors.read',
                'attachments.read',
                'minor_exits.read',
                'minor_activities.read',
                'minor_approaches.read',
                'minor_journals.read',
                'staff_shift_assignments.read',
                'staff_attendance_events.create',
                'staff_attendance_events.read',
                'staff_attendance_events.update',
                'staff_timesheet_entries.read',
                'staff_timesheet_entries.submit',
                'staff_timesheet_adjustments.create',
                'staff_timesheet_adjustments.read',
                'internal_messages.read',
            ],
            'ASSISTENTE_SOCIALE_EST' => [
                'minors.read',
                'minor_contacts.read',
                'attachments.read',
                'minor_exits.read',
                'minor_activities.read',
                'minor_approaches.read',
                'minor_journals.read',
            ],
            'SUPERVISORE_ESTERNO' => [
                'audit_logs.read',
            ],
        ];

        foreach (['SUPER_ADMIN', 'DIRETTORE', 'COORDINATORE', 'REFERENTE_STRUTTURA'] as $roleCode) {
            $grants[$roleCode] = array_merge($grants[$roleCode], ['staff_evaluations.read', 'staff_evaluations.manage', 'facility_bulletins.read', 'facility_bulletins.manage', 'facility_bulletins.publish', 'facility_bulletins.acknowledge']);
        }

        foreach (['PSICOLOGO', 'PEDIATRA', 'EDUCATORE', 'EDUCATORE_NOTTURNO', 'ASSISTENTE_SOCIALE_EST'] as $roleCode) {
            $grants[$roleCode] = array_merge($grants[$roleCode], ['facility_bulletins.read', 'facility_bulletins.acknowledge']);
        }

        $grants['ADMIN_IT'] = array_merge($grants['ADMIN_IT'], ['incident_types.create', 'incident_types.read', 'incident_types.update', 'incident_types.delete']);
        $grants['DIRETTORE'] = array_merge($grants['DIRETTORE'], ['incident_types.create', 'incident_types.read', 'incident_types.update', 'incident_types.delete', 'minor_incidents.create', 'minor_incidents.read', 'minor_incidents.update', 'minor_incidents.export']);
        foreach (['COORDINATORE', 'REFERENTE_STRUTTURA'] as $roleCode) {
            $grants[$roleCode] = array_merge($grants[$roleCode], ['incident_types.read', 'minor_incidents.create', 'minor_incidents.read', 'minor_incidents.update', 'minor_incidents.export']);
        }
        foreach (['PSICOLOGO', 'EDUCATORE', 'EDUCATORE_NOTTURNO'] as $roleCode) {
            $grants[$roleCode] = array_merge($grants[$roleCode], ['incident_types.read', 'minor_incidents.create', 'minor_incidents.read', 'minor_incidents.update']);
        }
        $grants['ASSISTENTE_SOCIALE_EST'] = array_merge($grants['ASSISTENTE_SOCIALE_EST'], ['incident_types.read', 'minor_incidents.read']);
        $grants['ADMIN_IT'] = array_merge($grants['ADMIN_IT'], ['medication_catalog.create', 'medication_catalog.read', 'medication_catalog.update', 'medication_catalog.delete']);
        $grants['DIRETTORE'] = array_merge($grants['DIRETTORE'], ['medication_catalog.create', 'medication_catalog.read', 'medication_catalog.update', 'medication_catalog.delete', 'minor_health.create', 'minor_health.read', 'minor_health.update', 'minor_health.administer', 'minor_health.export']);
        $grants['PEDIATRA'] = array_merge($grants['PEDIATRA'], ['medication_catalog.read', 'minor_health.create', 'minor_health.read', 'minor_health.update', 'minor_health.export']);
        foreach (['EDUCATORE', 'EDUCATORE_NOTTURNO'] as $roleCode) $grants[$roleCode] = array_merge($grants[$roleCode], ['medication_catalog.read', 'minor_health.read', 'minor_health.administer']);

        foreach ($grants as $roleCode => $permissionCodes) {
            $role = $roleModels[$roleCode];
            $role->permissions()->sync(
                collect($permissionCodes)
                    ->map(fn (string $code) => $permissionModels[$code]->id)
                    ->all()
            );
        }
    }
}
