<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;
use App\Models\{Medication,MedicationAdministrationOutcome,MedicationAdministrationRoute,MedicationDosageUnit,Minor,MinorDocument,MinorMedicationPlan,StaffMember};
use App\Services\{AuditLogService,MinorAccessService,MinorHistoryService};
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\UniqueConstraintViolationException;
use Illuminate\Http\{JsonResponse,Request};
use Illuminate\Support\Carbon;
use Illuminate\Validation\Rule;
class MinorMedicationController extends Controller
{
 public function __construct(private readonly MinorAccessService $access=new MinorAccessService(),private readonly MinorHistoryService $history=new MinorHistoryService(),private readonly AuditLogService $audit=new AuditLogService()){}
 public function options(Request $r):JsonResponse{$d=$r->validate(['facility_id'=>['required','integer','exists:facilities,id']]);$facility=(int)$d['facility_id'];abort_unless($r->user()->hasPermission('minor_health.read',$facility),403,'Accesso sanitario non consentito per questa struttura.');return response()->json(['medications'=>Medication::where('is_active',true)->orderBy('name')->get(),'dosage_units'=>MedicationDosageUnit::where('is_active',true)->orderBy('sort_order')->get(),'administration_routes'=>MedicationAdministrationRoute::where('is_active',true)->orderBy('sort_order')->get(),'outcomes'=>MedicationAdministrationOutcome::orderBy('sort_order')->get(),'prescribers'=>StaffMember::query()->where('facility_id',$facility)->whereIn('qualification_code',['PEDIATRA','MEDICO_BASE'])->orderBy('last_name')->get()]);}
 public function index(Request $r):JsonResponse{$q=MinorMedicationPlan::with($this->relations())->when($r->filled('facility_id'),fn($q)=>$q->where('facility_id',$r->integer('facility_id')))->when($r->filled('minor_id'),fn($q)=>$q->where('minor_id',$r->integer('minor_id')))->when($r->boolean('active_only',true),fn($q)=>$q->where('is_active',true))->whereHas('minor',fn(Builder $q)=>$this->access->scopeVisibleMinorsForUser($q,$r->user()))->orderByDesc('start_date');return response()->json($q->get());}
 public function store(Request $r):JsonResponse{$d=$this->validatePlan($r);$minor=Minor::findOrFail($d['minor_id']);$this->authorize($r,$minor,'minor_health.create');$this->assertLinks($minor,$d);$plan=MinorMedicationPlan::create([...$d,'facility_id'=>$minor->facility_id,'created_by_user_id'=>$r->user()->id,'updated_by_user_id'=>$r->user()->id]);$this->record($r,$plan,'create','ha creato un piano farmacologico');return response()->json($plan->load($this->relations()),201);}
 public function show(Request $r,MinorMedicationPlan $plan):JsonResponse{$this->authorize($r,$plan->minor,'minor_health.read');return response()->json($plan->load($this->relations()));}
 public function update(Request $r,MinorMedicationPlan $plan):JsonResponse{$this->authorize($r,$plan->minor,'minor_health.update');$d=$this->validatePlan($r,true,$plan);$this->assertLinks($plan->minor,$d);$plan->update([...$d,'updated_by_user_id'=>$r->user()->id]);$this->record($r,$plan,'update','ha aggiornato un piano farmacologico');return response()->json($plan->fresh()->load($this->relations()));}
 public function storeSchedule(Request $r,MinorMedicationPlan $plan):JsonResponse{$this->authorize($r,$plan->minor,'minor_health.update');abort_unless($plan->is_active,409,'Piano farmacologico non attivo.');$d=$r->validate(['time_of_day'=>['required','date_format:H:i'],'days_of_week'=>['required','array','min:1'],'days_of_week.*'=>['string',Rule::in(['MON','TUE','WED','THU','FRI','SAT','SUN'])],'as_needed'=>['sometimes','boolean']]);$s=$plan->schedules()->create([...$d,'created_by_user_id'=>$r->user()->id]);$this->record($r,$plan,'schedule_create','ha aggiunto un orario farmacologico');return response()->json($s,201);}
 public function administrations(Request $r,MinorMedicationPlan $plan):JsonResponse{$this->authorize($r,$plan->minor,'minor_health.read');return response()->json($plan->administrations()->with(['schedule','outcome','administeredBy:id,first_name,last_name,email'])->orderByDesc('scheduled_for')->get());}
 public function administer(Request $r,MinorMedicationPlan $plan):JsonResponse{$this->authorize($r,$plan->minor,'minor_health.administer');abort_unless($plan->is_active && (!$plan->end_date || !$plan->end_date->isPast()),409,'Piano farmacologico non attivo o scaduto.');$d=$r->validate(['medication_schedule_id'=>['nullable','integer','exists:minor_medication_schedules,id'],'scheduled_for'=>['required','date'],'administered_at'=>['nullable','date','before_or_equal:now'],'outcome_code'=>['required','string','exists:medication_administration_outcomes,code'],'notes'=>['nullable','string','max:4000']]);if(isset($d['medication_schedule_id']))abort_unless($plan->schedules()->whereKey($d['medication_schedule_id'])->exists(),422,'Orario non appartenente al piano.');$d['scheduled_for']=Carbon::parse($d['scheduled_for'])->format('Y-m-d H:i:s');abort_if($plan->administrations()->where('scheduled_for',$d['scheduled_for'])->exists(),409,'Somministrazione già registrata per data e ora indicate.');$outcome=MedicationAdministrationOutcome::where('code',$d['outcome_code'])->firstOrFail();unset($d['outcome_code']);try{$a=$plan->administrations()->create([...$d,'outcome_id'=>$outcome->id,'administered_at'=>$d['administered_at']??($outcome->code==='ADMINISTERED'?now():null),'administered_by_user_id'=>$r->user()->id,'signature_type'=>'authenticated_application_signature','signed_at'=>now()]);}catch(UniqueConstraintViolationException){abort(409,'Somministrazione già registrata per data e ora indicate.');}$this->record($r,$plan,'administration_signed','ha registrato e firmato una somministrazione');return response()->json($a->load(['schedule','outcome','administeredBy:id,first_name,last_name,email']),201);}
 public function alerts(Request $r):JsonResponse{$days=min(180,max(1,$r->integer('days',30)));$q=MinorMedicationPlan::with($this->relations())->where('is_active',true)->whereNotNull('end_date')->whereDate('end_date','<=',now()->addDays($days))->when($r->filled('facility_id'),fn($q)=>$q->where('facility_id',$r->integer('facility_id')))->whereHas('minor',fn(Builder $q)=>$this->access->scopeVisibleMinorsForUser($q,$r->user()))->orderBy('end_date');return response()->json($q->get()->map(fn($p)=>[...$p->toArray(),'alert_status'=>$p->end_date->isPast()?'expired':'expiring','days_until_expiry'=>now()->startOfDay()->diffInDays($p->end_date,false)]));}
 private function validatePlan(Request $r,bool $partial=false,?MinorMedicationPlan $plan=null):array{$p=$partial?'sometimes':'required';$endDateRule=$partial&&$plan?'after_or_equal:'.$plan->start_date->format('Y-m-d'):'after_or_equal:start_date';return $r->validate(['minor_id'=>[$partial?'prohibited':'required','integer','exists:minors,id'],'medication_id'=>[$p,'integer','exists:medications,id'],'dose_quantity'=>[$p,'numeric','gt:0'],'dosage_unit_id'=>[$p,'integer','exists:medication_dosage_units,id'],'administration_route_id'=>[$p,'integer','exists:medication_administration_routes,id'],'prescriber_staff_member_id'=>[$p,'integer','exists:staff_members,id'],'prescription_minor_document_id'=>['nullable','integer','exists:minor_documents,id'],'start_date'=>[$p,'date'],'end_date'=>['nullable','date',$endDateRule],'instructions'=>['nullable','string','max:10000'],'is_active'=>['sometimes','boolean']]);}
 private function assertLinks(Minor $m,array $d):void{if(isset($d['prescriber_staff_member_id']))abort_unless(StaffMember::whereKey($d['prescriber_staff_member_id'])->where('facility_id',$m->facility_id)->whereIn('qualification_code',['PEDIATRA','MEDICO_BASE'])->exists(),422,'Prescrittore non valido per la struttura.');if(isset($d['prescription_minor_document_id']))abort_unless(MinorDocument::whereKey($d['prescription_minor_document_id'])->where('minor_id',$m->id)->exists(),422,'Ricetta non appartenente al minore.');}
 private function authorize(Request $r,Minor $m,string $p):void{abort_unless($this->access->canAccessMinor($r->user(),$m,$p),403,'Accesso sanitario non consentito per questo minore.');}
 private function relations():array{return ['minor.minorStatus','medication','dosageUnit','administrationRoute','prescriber.qualificationLookup','prescriptionDocument.documentType','schedules','administrations.outcome','administrations.administeredBy:id,first_name,last_name,email'];}
 private function record(Request $r,MinorMedicationPlan $p,string $a,string $v):void{$p->loadMissing(['minor','medication']);$s=$this->audit->resolveActorDisplayName($r->user())." $v per ".$p->minor->publicDisplayName().'.';$this->history->record($p->minor,'minor_medication_'.$a,$r->user(),['minor_medication_plan_id'=>$p->id,'medication_code'=>$p->medication?->code,'operation_summary'=>$s]);$this->audit->record($r,['facility_id'=>$p->facility_id,'minor_id'=>$p->minor_id,'action'=>$a,'resource_type'=>'minor_medication_plan','resource_id'=>(string)$p->id,'resource_label'=>$p->medication?->name,'operation_summary'=>$s]);$this->audit->markHandled($r);}
}
